- name: variable from PLAY level
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Sivakumar"
    Duration: "110hrs"
  tasks:
  - name: check varaibles
    ansible.builtin.debug:
      msg: "Hi, I am learing {{Course}}, Trainer is {{Sivakumar}}, Duration is {{110hrs}}"
    