# TASK type variables
- name: variables from PLAY level
  hosts: localhost
  Vars:
    Course: "Devops"
    Trainer: "Sivakumar"
    Duration: "110hrs"
  tasks:
  - name: check variables
    vars: #task level
      Course: "Devops with AWS"
    ansible.bultin.debug:
      msg: "Hi, I am learning Course {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"