- name: conditions
  hosts: localhost
  tasks:
  - name: check roboshop user exists or not
    ansible.builtin.debug: id roboshop
    register: user # user is variale name
    ignore_erros: true # ansible will not exit even got error

  - name: print variable value
    ansible.builtin.debug:
      msg: "User output is: {{user}}"
      
