- name: loop
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.debug:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix
    